### ISSUE TITLE
hyh - Unsafe truncation casting is used for a number of state variables, including uncapped ones

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-ajna-judging#46]
hyh

medium

# Unsafe truncation casting is used for a number of state variables, including uncapped ones
## Summary

`inflator`, `bondSize`, `t0ThresholdPrice` are truncated in the logic without overflow checks.

## Vulnerability Detail

Although the probabilities of reaching the corresponding limits are very small, the consequences of material truncations is pool accounting corruption.

## Impact

If truncation does happen, then it will facilitate massive losses for pool users, say `inflator` one will reset the balances. Future code evolution inheriting the logic might end up having substantially bigger probabilities of reaching the type limits.

## Code Snippet

`poolState_.inflator` isn't capped:

https://github.com/sherlock-audit/2023-09-ajna/blob/main/ajna-core/src/base/Pool.sol#L542-L573

```solidity
    function _accruePoolInterest() internal returns (PoolState memory poolState_) {
        ...

            // if new interest may have accrued, call accrueInterest function and update inflator and debt fields of poolState_ struct
            if (poolState_.isNewInterestAccrued) {
>>              (uint256 newInflator, uint256 newInterest) = PoolCommons.accrueInterest(
                    ...
                );
>>              poolState_.inflator = newInflator;
                // After debt owed to lenders has accrued, calculate current debt owed by borrowers
                poolState_.debt = Maths.wmul(poolState_.t0Debt, poolState_.inflator);
```

https://github.com/sherlock-audit/2023-09-ajna/blob/main/ajna-core/src/libraries/external/PoolCommons.sol#L220-L231

```solidity
    function accrueInterest(
        EmaState      storage emaParams_,
        DepositsState storage deposits_,
        PoolState calldata poolState_,
        uint256 thresholdPrice_,
        uint256 elapsed_
    ) external returns (uint256 newInflator_, uint256 newInterest_) {
        // Scale the borrower inflator to update amount of interest owed by borrowers
>>      uint256 pendingFactor = PRBMathUD60x18.exp((poolState_.rate * elapsed_) / 365 days);

        // calculate the highest threshold price
>>      newInflator_ = Maths.wmul(poolState_.inflator, pendingFactor);
```

At some point very distant point it will be silently truncated with disastrous debt state resetting outcome:

https://github.com/sherlock-audit/2023-09-ajna/blob/main/ajna-core/src/base/Pool.sol#L678-L687

```solidity
    function _updateInterestState(
        PoolState memory poolState_,
        uint256 lup_
    ) internal {

        PoolCommons.updateInterestState(interestState, emaState, deposits, poolState_, lup_);

        // update pool inflator
        if (poolState_.isNewInterestAccrued) {
            inflatorState.inflator       = uint208(poolState_.inflator);
```

Also, for completness, notice that `vars.bondChange` is truncated in `_rewardTake()`:

https://github.com/sherlock-audit/2023-09-ajna/blob/main/ajna-core/src/libraries/external/TakerActions.sol#L565-L583

```solidity
    function _rewardTake(
        AuctionsState storage auctions_,
        Liquidation storage liquidation_,
        TakeLocalVars memory vars
    ) internal {
        if (vars.isRewarded) {
            // take is below neutralPrice, Kicker is rewarded
>>          liquidation_.bondSize                 += uint160(vars.bondChange);
            auctions_.kickers[vars.kicker].locked += vars.bondChange;
            auctions_.totalBondEscrowed           += vars.bondChange;
        } else {
            // take is above neutralPrice, Kicker is penalized
            vars.bondChange = Maths.min(liquidation_.bondSize, vars.bondChange);

>>          liquidation_.bondSize                 -= uint160(vars.bondChange);
            auctions_.kickers[vars.kicker].locked -= vars.bondChange;
            auctions_.totalBondEscrowed           -= vars.bondChange;
        }
    }
```

And in `_rewardBucketTake()`:

https://github.com/sherlock-audit/2023-09-ajna/blob/main/ajna-core/src/libraries/external/TakerActions.sol#L652-L660

```solidity
        } else {
            // take is above neutralPrice, Kicker is penalized
            vars.bondChange = Maths.min(liquidation_.bondSize, vars.bondChange);

>>          liquidation_.bondSize -= uint160(vars.bondChange);

            auctions_.kickers[vars.kicker].locked -= vars.bondChange;
            auctions_.totalBondEscrowed           -= vars.bondChange;
        }
```

`t0ThresholdPrice` is truncated in `update()`:

https://github.com/sherlock-audit/2023-09-ajna/blob/main/ajna-core/src/libraries/internal/Loans.sol#L83-L94

```solidity
        uint256 t0ThresholdPrice = activeBorrower ? Maths.wdiv(borrower_.t0Debt, borrower_.collateral) : 0;

        // loan not in auction, update threshold price and position in heap
        if (!inAuction_ ) {
            // get the loan id inside the heap
            uint256 loanId = loans_.indices[borrowerAddress_];
            if (activeBorrower) {
                // revert if threshold price is zero
                if (t0ThresholdPrice == 0) revert ZeroThresholdPrice();

                // update heap, insert if a new loan, update loan if already in heap
>>              _upsert(loans_, borrowerAddress_, loanId, uint96(t0ThresholdPrice));
```

## Tool used

Manual Review

## Recommendation

For the sake of unification and eliminating these considerations consider using `SafeCast` in all the occurrences above, e.g.:

https://github.com/sherlock-audit/2023-09-ajna/blob/main/ajna-core/src/libraries/external/KickerActions.sol#L396-L411

```solidity
    function _recordAuction(
        ...
    ) internal {
        // record liquidation info
        liquidation_.kicker         = msg.sender;
        liquidation_.kickTime       = uint96(block.timestamp);
        liquidation_.referencePrice = SafeCast.toUint96(referencePrice_);
        liquidation_.bondSize       = SafeCast.toUint160(bondSize_);
        liquidation_.bondFactor     = SafeCast.toUint96(bondFactor_);
        liquidation_.neutralPrice   = SafeCast.toUint96(neutralPrice_);
```

**Comment by nevillehuang** [comment]
Escalate, considering the following should be low severity/invalid

1. Watson is saying probabilities of reaching limits are very small, but does not provide a concrete examples (with values) of it reaching this

> Although the probabilities of reaching the corresponding limits are very small, the consequences of material truncations is pool accounting corruption.

2. Watson is speculating on future code evolution/integration, which is invalid based on sherlock [rules](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid)

> Future code evolution inheriting the logic might end up having substantially bigger probabilities of reaching the type limits

> 22. Future issues: Issues that result out of a future integration/implementation that was not intended (mentioned in the docs/README) or because of a future change in the code (as a fix to another issue) are not valid issues

**Comment by sherlock-admin2** [comment]
> Escalate, considering the following should be low severity/invalid
> 
> 1. Watson is saying probabilities of reaching limits are very small, but does not provide a concrete examples (with values) of it reaching this
> 
> > Although the probabilities of reaching the corresponding limits are very small, the consequences of material truncations is pool accounting corruption.
> 
> 2. Watson is speculating on future code evolution/integration, which is invalid based on sherlock [rules](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid)
> 
> > Future code evolution inheriting the logic might end up having substantially bigger probabilities of reaching the type limits
> 
> > 22. Future issues: Issues that result out of a future integration/implementation that was not intended (mentioned in the docs/README) or because of a future change in the code (as a fix to another issue) are not valid issues
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by neeksec** [comment]
Agree with Escalation this should be low.

**Comment by Evert0x** [comment]
@dmitriia any argument on this? If not I will plan to make low/invalid.

**Comment by dmitriia** [comment]
> @dmitriia any argument on this? If not I will plan to make low/invalid.

Not entirely sure that the escalation has valid grounds, i.e. the issue is absolutely straightforward, not complex, and based on what rule the impact should be showcased here, but not in #49, as an example? Low effort escalations like this can ideally be denied due to the lack of proper justification.

The issue is an example of very low probability (lots of time need to pass for the impact to emerge) and very high impact (the breakage of pool's accounting with all the depositors losing their funds and borrowers having their debt written off), which counterweight each other. Rules wise it fits into `'Causes a loss of funds but requires certain external conditions or specific states'` category.

I.e. as an example, truncating inflator will break the accounting of the pool, with all the depositors permanently losing access to their funds at once being one of the outcomes:

https://github.com/sherlock-audit/2023-09-ajna-dmitriia/blob/d8b173d43482ef50c1fafb05ff1aef6fda4a3c82/ajna-core/src/base/Pool.sol#L686-L691

```solidity
        if (poolState_.isNewInterestAccrued) {
>>          inflatorState.inflator       = uint208(poolState_.inflator);
            inflatorState.inflatorUpdate = uint48(block.timestamp);
        // if the debt in the current pool state is 0, also update the inflator and inflatorUpdate fields in inflatorState
        // slither-disable-next-line incorrect-equality
        }
```

For this to emerge, the extreme rates need to take place for a long time, say overflow will happen at pool having `1500%` rate for 160 years, `(20)**160 / 1e208 = 1.46..`.

Such rates were already reached [live](https://info.ajna.finance/ethereum/pools/0xdb30a08ebc49af1baf87f57824f85056ced33d5f) in the first version of the protocol.

Now there is a `400%` cap for pool's rate, so more years are needed to reach that state, `(4)**346 / 1e208 = 2.0..`, but the exact number doesn't matter as the pools are perpetual.

**Comment by nevillehuang** [comment]
@dmitriia I have deep respect for you as a security researcher, and didn’t mean any bad intentions. My idea of escalating is because I honestly felt this submission lacks in depth description of the possible truncation, so I raised it. 

Im not sure about the delegation of burden of in terms of escalator and auditor, but I was under the impression that this burden of proof is not on you not me. If thats not the case, I apologize and will put more thought into my escalations in the future.

However, based on ur explanation above (correct me if im wrong), are u saying it takes a minimum of 100+ years to overflow? If thats the case I still stand by keeping this issue low severity.

**Comment by dmitriia** [comment]
The math in my post above needed to be corrected, done now. It's 90 years at `400%` rate, which limitation is the only mitigation in place for that part.

Also, `uint96(t0ThresholdPrice)` breaks when price is greater than `7.9e28`, `uint160(vars.bondChange)` breaks when bond is greater than `1.46e48`. Those values are extreme, but there is a positive probability of reaching those for some combinations of quote and collateral tokens in the future. Similarly to #30 this continues the discussion of better handling of the extreme token combinations, that are relevant given permissionless nature of Ajna pool creation.

This is for low probability part, and given pool breaking / direct user fund loss impact, which is basically critical (as it usually is with truncations), per `'Causes a loss of funds but requires certain external conditions or specific states'` looks like valid medium.

**Comment by nevillehuang** [comment]
Ok I will need to go more in-depth in the calculations and come back to you. On first look I’m still not convinced since the truncation logic revolves around reward take and accruing interest mechanisms which makes truncation less likely.

Will also look into #30 more and take it into consideration.

**Comment by Czar102** [comment]
It seems to me that the Watson challenges the design choices (parameter limits) of the protocol, which is out of scope. This describes `t0ThresholdPrice` and `vars.bondChange` casting. Concerning the casting of `poolState_.inflator`, it looks like reverting won't make the situation better – updates may be impossible and it will DoS the functionality anyway? Would like to hear more thoughts on it @dmitriia.

It seems to me that those limits are protocol team's design choices and those are not considered issues.

Concerning the burden of proof @nevillehuang @dmitriia. The burned of proof lies on the party that wants their submission/escalation to be considered valid/accepted. During judging, the burden of proof lies on the Watson. During the escalation phase, the burden of proof (of validity/duplication status) lies on the escalator.

Anyway, I agree with @nevillehuang that this submission is not a high-effort one. I also think that @nevillehuang shared his concerns in both an informative and a concise way.
> Low effort escalations like this can ideally be denied due to the lack of proper justification.

I don't see a reason why would anyone consider this escalation a low-effort one. @nevillehuang presented a valid concern about this issue. The Watson did not present enough information to judge the severity of the issue solely based on the submission. Instead of a detailed impact description, the only grounds on which one can determine the severity of the finding is Watson's opinion:
> Although the probabilities of reaching the corresponding limits are very small, the consequences of material truncations is pool accounting corruption.

**Comment by dmitriia** [comment]
As far as I see, whether or not `t0ThresholdPrice` and `bondChange` approach danger zones look to be the functions of collateral token price in quote token terms, not protocol settings by itself.

I.e. pools with some very cheap quote and costly collateral token combinations can be in trouble, even if all other protocol structures fully allow highly elevated prices, so it can be said that protocol accepts those by design, but in the mentioned pieces of code the truncation will still ruin the accounting. And this is just a logic malfunction, not something intended.

**Comment by dmitriia** [comment]
Regarding accumulators this is an interesting question, you are right that some special treatment is needed to properly manage the overflows. Safe casting is the default approach now used almost everywhere, but for state variables like `inflator` it's not enough as reverting will mean massive fund freeze, that is not desired more than truncation and massive fund transfer from lenders to borrowers, which happens when `inflator` being silently truncated as all deposits and loans are being written off this way. 

One possible solution might be introducing a pool retirement mode where only repayments/withdrawals are allowed. This mode can be entered when any core accumulator exceeds some threshold, say half of the maximum value of the chosen type, say whenever `2^128` is reached within `uint256` based accounting. This way users will be notified far beforehand and will have plenty of time to react.

**Comment by Czar102** [comment]
> I.e. pools with some very cheap quote and costly collateral token combinations can be in trouble, even if all other protocol structures fully allow highly elevated prices, so it can be said that protocol accepts those by design, but in the mentioned pieces of code the truncation will still ruin the accounting.

Maybe this protocol structure was "the bottleneck" of the system by design? I think it is quite fair to assume that.
Additionally, the report doesn't present any scenarios where this truncation would cause an exploit and other functionality works properly. It is not Judges' job to check if that is possible. The Watson should have checked it and shown it during the time of the contest in their submission.

Planning to accept the escalation and make the issue low severity.

**Comment by dmitriia** [comment]
Well, for truncation cases the exploits are straightforward, it is basically corrupted accounting with direct loss for the corresponding beneficiary.

I think the impact is clearly outlined in the initial submission, for the most severe `inflator` case:

> ### Impact

> If truncation does happen, then it will facilitate massive losses for pool users, say inflator one will reset the balances.

Resetting the balances means deposits and loans are being written off, I view this as something self-explanatory.

**Comment by Czar102** [comment]
It is self-explanatory, but again, I think it is a design limitation.
> Ok I will need to go more in-depth in the calculations and come back to you.

This wouldn't be said if the Watson mentioned the limitations of the possible exploit. The reader should know whether the contract may misbehave after 1000 years, or 10 days, right? And every reader shouldn't try to figure that out by themself.

@ith-harvey would like you to check this issue despite it being a low severity issue to make sure that the team is aware of the mentioned limitations. Also, when the inflator would overflow, it may be a good idea to set it at a max value not to decrease everyone's debt/share balance.

**Comment by Czar102** [comment]
Result:
Low
Unique

**Comment by sherlock-admin2** [comment]
The escalations could not be resolved because the issue failed the following checks:

- [nevillehuang's escalation](https://github.com/sherlock-audit/2023-09-ajna-judging/issues/46/#issuecomment-1799618213) could not be resolved, because it has 0 or more than 1 judge reactions.

**Comment by ith-harvey** [comment]
fixed -> https://github.com/ajna-finance/contracts/pull/](https://github.com/ajna-finance/contracts/pull/967

**Comment by dmitriia** [comment]
Fix looks ok
