### ISSUE TITLE
hyh - settlePoolDebt places the collateral to the lowest bucket, allowing for stealing it with back-running

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-ajna-judging#52]
hyh

medium

# settlePoolDebt places the collateral to the lowest bucket, allowing for stealing it with back-running
## Summary

SettlerActions's `_settleAuction()` and `_settlePoolDebtWithDeposit()` run from `settlePoolDebt()` always put remainder and compensated collateral of a borrower in the lowest bucket, where is can be straightforwardly stolen by back-running the function.

## Vulnerability Detail

For the borrower these funds are accessible no matter what bucket they are placed to. In the same time, when the bucket is below the market, these funds are free for anyone to obtain, pocketing the difference. SettlerActions's logic places them into the lowest bucket, despite being able to use quote deposit distribution information to gauge the price. Also, it might be a successful auction at the start and what is settled is only the remainder, so the executed auction price can be used. The issue is that setting the price too small allows for straightforward stealing, while using price too big only creates harmless above market `ask` from the borrower.

The fact that there are no deposits left (for `_settlePoolDebtWithDeposit()`) or that some part of the debt wasn't bought on auction (for `_settleAuction()` run from `settlePoolDebt()`) doesn't form enough grounds for estimating the fair price being equal to the lowest bucket's one. Lack of deposits can be of a technical nature (for example, drawing debt creates immediate debt overhang formed by a borrowing fee), while leaving minimal debt not bought at any price can be due to, as an example: pool doesn't have many participants overall, say some not too liquid NFT with small volumes, there was an initial taker, who left close to minimal debt due to oversight/own liquidity reasons (or knowing that there can be a situation of lack of interest and trying to exploit it), minimal debt is small in this pool, gas prices rocketed for some reasons, so taking the remaining part was not profitable, so the auction had no bids for the remainder and has to be cleared later with `settlePoolDebt()` in a calmer market.

## Impact

Borrower will lose all the placed collateral as anyone can run its extraction right after the settlement.

## Code Snippet

Bucket for collateral remainder is determined as if auction is taking place now:

https://github.com/sherlock-audit/2023-09-ajna/blob/main/ajna-core/src/libraries/external/SettlerActions.sol#L206-L244

```solidity
    function _settleAuction(
        ...
    ) internal returns (uint256 remainingCollateral_, uint256 compensatedCollateral_) {

        if (poolType_ == uint8(PoolType.ERC721)) {
            uint256 lp;
            uint256 bucketIndex;

            // floor collateral of borrower
            remainingCollateral_ = (borrowerCollateral_ / Maths.WAD) * Maths.WAD;

            // if there's fraction of NFTs remaining then reward difference to borrower as LP in auction price bucket
            if (remainingCollateral_ != borrowerCollateral_) {

                // calculate the amount of collateral that should be compensated with LP
                compensatedCollateral_ = borrowerCollateral_ - remainingCollateral_;

>>              uint256 auctionPrice = _auctionPrice(
                    auctions_.liquidations[borrowerAddress_].referencePrice,
                    auctions_.liquidations[borrowerAddress_].kickTime
                );

                // determine the bucket index to compensate fractional collateral
>>              bucketIndex = auctionPrice > MIN_PRICE ? _indexOf(auctionPrice) : MAX_FENWICK_INDEX;

                // deposit collateral in bucket and reward LP to compensate fractional collateral
                lp = Buckets.addCollateral(
                    buckets_[bucketIndex],
                    borrowerAddress_,
                    Deposits.valueAt(deposits_, bucketIndex),
                    compensatedCollateral_,
                    _priceAt(bucketIndex)
                );
            }
```

When `SettlerActions._settleAuction()` is called from `TakerActions._takeLoan()` it is reasonable, but when it's called from `SettlerActions.settlePoolDebt()` and collateral isn't zero it is always `block.timestamp - kickTime > 72 hours`, i.e. auction price above will be close to zero as auction was ended:

https://github.com/sherlock-audit/2023-09-ajna/blob/main/ajna-core/src/libraries/external/SettlerActions.sol#L100-L113

```solidity
    function settlePoolDebt(
        AuctionsState storage auctions_,
        mapping(uint256 => Bucket) storage buckets_,
        DepositsState storage deposits_,
        LoansState storage loans_,
        ReserveAuctionState storage reserveAuction_,
        PoolState calldata poolState_,
        SettleParams memory params_
    ) external returns (SettleResult memory result_) {
        uint256 kickTime = auctions_.liquidations[params_.borrower].kickTime;
        if (kickTime == 0) revert NoAuction();

        Borrower memory borrower = loans_.borrowers[params_.borrower];
>>      if ((block.timestamp - kickTime <= 72 hours) && (borrower.collateral != 0)) revert AuctionNotClearable();
```

Similarly, it is the lowest bucket whenever all deposits happen to be used:

https://github.com/sherlock-audit/2023-09-ajna/blob/main/ajna-core/src/libraries/external/SettlerActions.sol#L347-L352

```solidity
            (vars.index, , vars.scale) = Deposits.findIndexAndSumOfSum(deposits_, 1);
            vars.hpbUnscaledDeposit    = Deposits.unscaledValueAt(deposits_, vars.index);
            vars.unscaledDeposit       = vars.hpbUnscaledDeposit;
            vars.price                 = _priceAt(vars.index);

>>          if (vars.unscaledDeposit != 0) {
```

https://github.com/sherlock-audit/2023-09-ajna/blob/main/ajna-core/src/libraries/external/SettlerActions.sol#L410-L421

```solidity
>>          } else {
                // Deposits in the tree is zero, insert entire collateral into lowest bucket 7388
                Buckets.addCollateral(
>>                  buckets_[vars.index],
                    params_.borrower,
                    0,  // zero deposit in bucket
                    remainingCollateral_,
>>                  vars.price
                );
                // entire collateral added into bucket, no borrower pledged collateral remaining
                remainingCollateral_ = 0;
            }
```

In both cases this lowest bucket might not correctly correspond to the market price of collateral and the funds placed this way can be stolen from the borrower by back-running such transaction with adding quote and remove collateral funds from this near zero bucket.

## Tool used

Manual Review

## Recommendation

As in both cases there were a settlement process across the deposit buckets taking place before, its information, say the average bid price, can be used for the placement, along with the latest take price, when available.

E.g. consider determining the best estimation of bid price this way, when available, and putting the funds in SettlerActions.sol#L206-L244 and SettlerActions.sol#L410-L421 there. Borrower will be able to remove them from any bucket, while the ability to steal from them will be reduced this way. I.e. if such bucket be above market it will just act as above-market offer, which is harmless.

**Comment by kadenzipfel** [comment]
Escalate

Invalid. You cannot arb collateral from the lowest price bucket and this issue fails to prove otherwise.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Invalid. You cannot arb collateral from the lowest price bucket and this issue fails to prove otherwise.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by neeksec** [comment]
> You cannot arb collateral from the lowest price bucket

I agree with escalation on this.
See if @dmitriia can provide additional proof.

**Comment by ith-harvey** [comment]
A couple comments in regards to how the protocol was designed that the Watson touches on but seemingly reinterprets:
- Borrowers do not place collateral or quote token directly in buckets. That functionality is reserved for the lender or arbitrageur.
- When settle occurs the outstanding debt in the loan (auction) must be dealt with. Collateral is then placed in the buckets  and lenders deposit that exist in those buckets are then canceled out. This is as designed since lenders bear the bad debt of a pool.
- There is also a deposit locking functionality... if the debt in the pool goes to auction then all deposit that supports that debt is locked. Although there are unique scenarios in which the debt can exceed the deposit, that is unrelated to this issue.

If no one bids in the auction and there is not enough deposit in the book to support the amount of collateral that can be inserted into those buckets the collateral is deemed worthless and is placed in the lowest bucket.

**Comment by dmitriia** [comment]
> the collateral is deemed worthless and is placed in the lowest bucket

This is exactly the issue described here. No bids in auction state can happen due to a number of reasons, not all of which mean that collateral is worthless. There is no downside in placing the collateral  in a bucket based on the price action information the system have.

**Comment by dmitriia** [comment]
> You cannot arb collateral from the lowest price bucket and this issue fails to prove otherwise

Can you elaborate or rephrase? It is [possible to add quote token](https://github.com/sherlock-audit/2023-09-ajna/blob/main/ajna-core/src/libraries/external/LenderActions.sol#L158) at `MAX_FENWICK_INDEX` and then remove collateral nearly for free.

**Comment by Evert0x** [comment]
@kadenzipfel can you respond to these comments?

**Comment by kadenzipfel** [comment]
My initial reasoning was incorrect but I stand by @ith-harvey's reasoning

**Comment by dmitriia** [comment]
@ith-harvey comments are correct, but do not invalidate the issue. It looks like the proper response here is acknowledging.

To reiterate, the approach of:

> > the collateral is deemed worthless and is placed in the lowest bucket

Causes the issue of collateral being sold for dust to any back-running actor:

> No bids in auction state can happen due to a number of reasons, not all of which mean that collateral is worthless. There is no downside in placing the collateral in a bucket based on the price action information the system have.

I.e. the system deems the collateral worthless, while it not might be worthless at all, so borrower might lose this not worthless collateral due to protocol logic. Placing it in a different bucket will not create any additional ways for borrower to profit off the system as the collateral is now returned to them for free, just being placed in a `free for all` bucket with only reason that auction finished with not enough bids to cover all the debt. This can happen due to market disruption / low liquidity conditions. The protocol is free to state this as a limitation of the logic, but the logic itself is described correctly in the issue and do produce the impact stated.

**Comment by kadenzipfel** [comment]
What are valid reasons for there to be no bids in the auction? It's completely rational to deem the collateral as worthless if no one is willing to pay for it at auction. Additionally, if the collateral is valuable and no ones buying, the borrower can simply buy it back at a very low price.

**Comment by dmitriia** [comment]
The situation of having not enough bidders during particular 72h auction window can happen due to temporary market disruption resulting in low liquidity conditions and losing interest in some areas of the market. This do not mean that collateral has no worth. This meant that there were no bidders in a particular period. Imagine you have a big warehouse to sell and run an auction for a week, and had some inquiries, but no bids. Does that mean that it worth zero?

Protocol can have a logic of ignoring such rare situations, but there the borrower can lose their collateral as described. It's a limitation that can be met with adjusting bucket price based on the information the system already has or acknowledged.

**Comment by Czar102** [comment]
If everyone can see the auction for your warehouse and no one is creating a bid for $1, then it means it's worth less for all people that saw it.

Anyway, considerations about the value of tokens are out of scope. As the Sponsor described, the auctions work as expected and I don't consider this as a vulnerability. This is how markets work and this is the model chosen by the team.

Design choices are not issues.

Will allow for final comments. Planning to accept the escalation and make the issue invalid.

**Comment by dmitriia** [comment]
What if the auction took place for 1 second, still the same conclusions? Time is relative, in this context the assumption that 72 hours is enough is based on underlying assumption of having calm and liquid market conditions. This, however, can change and, as an example, in a sharp downturn and illiquid conditions this might be very well not enough.

Or, to introduce somewhat other perspective, the collateral might had a zero valuation briefly in the end of auction, but it quickly returned to normal as long as market conditions abated, but the auction has ended at that point. The thing is the collateral belongs to borrower anyway and placing it in this or that bucket does not benefit or hurt protocol in any way. But placing it low can damage the borrower in this situation.

The issue is for post-auction collateral treatment, not for auctions themselves. The root cause is that having no bids in a particular timeframe by itself does not mean zero valuation, it is an assumption of the logic that can be easily enhanced as the protocol do have the price information, which is disregarded, i.e. overwritten by the auction.

What @ith-harvey outlined is correct, but rather describes the issue in the different words. I.e. yes, it is true that `If no one bids in the auction and there is not enough deposit in the book to support the amount of collateral that can be inserted into those buckets the collateral is deemed worthless and is placed in the lowest bucket`, and exactly this allows for the non-zero worth collateral stealing described.

I don't think this is what is usually called as a design choice, it is rather a situation when the code assumes that a ERC20 token will revert on a failed transfer, but it rather returns false, which is also the allowed behavior per the standard. Here the market conditions are assumed, but it can be different, and neither Ajna describes calm market conditions as a prerequisite for protocol to work, nor any other mechanics guarantee that it will be liquid all the time. If they are not, the settlement logic allows for borrower to be exploited.

**Comment by Czar102** [comment]
> it is an assumption of the logic that can be easily enhanced

It is a design choice. It assumes some properties of a market. Ability to enhance is not an issue. If we considered that the "time is relative", even 6 months would be too little time for an auction. Or maybe right after the 6 month auction the price goes up again? These market or price considerations are out of scope.

Also, I think the borrower can also participate in an auction. So they can bid for the lowest price possible and won't give out collateral for free.

**Comment by Czar102** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [kadenzipfel](https://github.com/sherlock-audit/2023-09-ajna-judging/issues/52/#issuecomment-1802953311): accepted
